import * as fs from 'fs';
import * as path from 'path';

// Read the NSE CSV file
const csvPath = path.join(__dirname, '..', 'data', 'nse_equity.csv');
const csvContent = fs.readFileSync(csvPath, 'utf-8');
const lines = csvContent.trim().split('\n');

// Parse NSE companies from CSV
// Format: SYMBOL,NAME OF COMPANY, SERIES, DATE OF LISTING, PAID UP VALUE, MARKET LOT, ISIN NUMBER, FACE VALUE
const nseCompanies: any[] = [];
for (let i = 1; i < lines.length; i++) {
  const parts = lines[i].split(',');
  if (parts.length < 2) continue;
  const symbol = parts[0].trim();
  const name = parts[1].trim();
  if (!symbol || !name) continue;
  
  nseCompanies.push({
    symbol: `${symbol}.NS`,
    name,
    exchange: 'NSE',
    sector: null,
    industry: null,
  });
}

console.log(`Parsed ${nseCompanies.length} NSE companies from CSV`);

// BSE companies - comprehensive list of BSE-only companies with their scrip codes
// These are companies primarily traded on BSE that may not be on NSE
const BSE_COMPANIES = [
  // BSE Sensex & Large Caps (BSE codes)
  { code: '500325', name: 'Reliance Industries Ltd', sector: 'Oil & Gas' },
  { code: '500112', name: 'Hindustan Zinc Ltd', sector: 'Mining' },
  { code: '500002', name: 'ABB India Ltd', sector: 'Engineering' },
  { code: '500003', name: 'Aegis Logistics Ltd', sector: 'Oil & Gas' },
  { code: '500008', name: 'Amara Raja Energy & Mobility', sector: 'Auto Components' },
  { code: '500010', name: 'HDFC Asset Management Co', sector: 'Finance' },
  { code: '500012', name: 'Andhra Paper Ltd', sector: 'Paper' },
  { code: '500013', name: 'Action Construction Equipment', sector: 'Engineering' },
  { code: '500014', name: 'Adani Power Ltd', sector: 'Power' },
  { code: '500020', name: 'Bank of Maharashtra', sector: 'Banking' },
  { code: '500023', name: 'Bharat Forge Ltd', sector: 'Auto Components' },
  { code: '500024', name: 'Bharat Gears Ltd', sector: 'Auto Components' },
  { code: '500027', name: 'BPL Ltd', sector: 'Electronics' },
  { code: '500028', name: 'Birla Corporation Ltd', sector: 'Cement' },
  { code: '500031', name: 'Carborundum Universal Ltd', sector: 'Engineering' },
  { code: '500033', name: 'Century Enka Ltd', sector: 'Textiles' },
  { code: '500034', name: 'Century Textiles & Industries', sector: 'Textiles' },
  { code: '500038', name: 'Chambal Fertilisers & Chemicals', sector: 'Fertilizers' },
  { code: '500039', name: 'Chennai Petroleum Corp', sector: 'Oil & Gas' },
  { code: '500040', name: 'CEAT Ltd', sector: 'Tyres' },
  { code: '500042', name: 'CESC Ltd', sector: 'Power' },
  { code: '500043', name: 'CG Power & Industrial Solutions', sector: 'Engineering' },
  { code: '500045', name: 'Chemplast Sanmar Ltd', sector: 'Chemicals' },
  { code: '500049', name: 'Cyient DLM Ltd', sector: 'Electronics' },
  { code: '500052', name: 'Dalmia Bharat Ltd', sector: 'Cement' },
  { code: '500055', name: 'DCM Shriram Ltd', sector: 'Chemicals' },
  { code: '500057', name: 'Deepak Fertilisers', sector: 'Fertilizers' },
  { code: '500058', name: 'Devyani International Ltd', sector: 'Food Services' },
  { code: '500060', name: 'DLF Ltd', sector: 'Real Estate' },
  { code: '500063', name: 'Dredging Corporation of India', sector: 'Shipping' },
  { code: '500067', name: 'EID Parry India Ltd', sector: 'Sugar' },
  { code: '500068', name: 'Electrosteel Castings Ltd', sector: 'Metals' },
  { code: '500071', name: 'Emami Ltd', sector: 'FMCG' },
  { code: '500072', name: 'Engineers India Ltd', sector: 'Engineering' },
  { code: '500078', name: 'Finolex Cables Ltd', sector: 'Electricals' },
  { code: '500079', name: 'Finolex Industries Ltd', sector: 'Plastics' },
  { code: '500082', name: 'Forbes & Company Ltd', sector: 'Engineering' },
  { code: '500085', name: 'Garden Reach Shipbuilders', sector: 'Defence' },
  { code: '500086', name: 'GlaxoSmithKline Pharma Ltd', sector: 'Pharma' },
  { code: '500087', name: 'Godfrey Phillips India Ltd', sector: 'FMCG' },
  { code: '500089', name: 'Godrej Industries Ltd', sector: 'Conglomerate' },
  { code: '500090', name: 'Grasim Industries Ltd', sector: 'Cement' },
  { code: '500093', name: 'Graphite India Ltd', sector: 'Metals' },
  { code: '500096', name: 'Gujarat Fluorochemicals Ltd', sector: 'Chemicals' },
  { code: '500100', name: 'Gujarat State Fertilizers', sector: 'Fertilizers' },
  { code: '500101', name: 'Grindwell Norton Ltd', sector: 'Engineering' },
  { code: '500103', name: 'Hawkins Cookers Ltd', sector: 'Consumer Durables' },
  { code: '500104', name: 'HEG Ltd', sector: 'Metals' },
  { code: '500106', name: 'Hindalco Industries Ltd', sector: 'Metals' },
  { code: '500108', name: 'Hindustan Construction Co', sector: 'Construction' },
  { code: '500109', name: 'Hindustan Copper Ltd', sector: 'Mining' },
  { code: '500110', name: 'Hindustan Oil Exploration', sector: 'Oil & Gas' },
  { code: '500111', name: 'Hindustan Petroleum Corp', sector: 'Oil & Gas' },
  { code: '500113', name: 'ICICI Securities Ltd', sector: 'Finance' },
  { code: '500114', name: 'IDBI Bank Ltd', sector: 'Banking' },
  { code: '500116', name: 'India Cements Ltd', sector: 'Cement' },
  { code: '500117', name: 'India Glycols Ltd', sector: 'Chemicals' },
  { code: '500119', name: 'Indian Overseas Bank', sector: 'Banking' },
  { code: '500120', name: 'Indo Count Industries Ltd', sector: 'Textiles' },
  { code: '500123', name: 'IFB Industries Ltd', sector: 'Consumer Durables' },
  { code: '500124', name: 'IFCI Ltd', sector: 'Finance' },
  { code: '500125', name: 'ITD Cementation India Ltd', sector: 'Construction' },
  { code: '500126', name: 'J B Chemicals & Pharma', sector: 'Pharma' },
  { code: '500127', name: 'JK Lakshmi Cement Ltd', sector: 'Cement' },
  { code: '500128', name: 'JK Paper Ltd', sector: 'Paper' },
  { code: '500129', name: 'JK Tyre & Industries Ltd', sector: 'Tyres' },
  { code: '500130', name: 'JSW Infrastructure Ltd', sector: 'Infrastructure' },
  { code: '500133', name: 'Jubilant Ingrevia Ltd', sector: 'Chemicals' },
  { code: '500135', name: 'KEC International Ltd', sector: 'Engineering' },
  { code: '500138', name: 'Kennametal India Ltd', sector: 'Engineering' },
  { code: '500140', name: 'KFIN Technologies Ltd', sector: 'Finance' },
  { code: '500142', name: 'Kirloskar Brothers Ltd', sector: 'Engineering' },
  { code: '500145', name: 'Kirloskar Ferrous Industries', sector: 'Metals' },
  { code: '500150', name: 'Kirloskar Oil Engines Ltd', sector: 'Engineering' },
  { code: '500155', name: 'KNR Constructions Ltd', sector: 'Construction' },
  { code: '500160', name: 'Kolte-Patil Developers Ltd', sector: 'Real Estate' },
  { code: '500163', name: 'KSB Ltd', sector: 'Engineering' },
  { code: '500164', name: 'Lakshmi Machine Works Ltd', sector: 'Engineering' },
  { code: '500165', name: 'Linde India Ltd', sector: 'Chemicals' },
  { code: '500168', name: 'Lumax Industries Ltd', sector: 'Auto Components' },
  { code: '500170', name: 'Mazagon Dock Shipbuilders', sector: 'Defence' },
  { code: '500171', name: 'MAS Financial Services', sector: 'Finance' },
  { code: '500175', name: 'Minda Corporation Ltd', sector: 'Auto Components' },
  { code: '500179', name: 'Mishra Dhatu Nigam Ltd', sector: 'Defence' },
  { code: '500180', name: 'MMTC Ltd', sector: 'Trading' },
  { code: '500182', name: 'Mold-Tek Packaging Ltd', sector: 'Packaging' },
  { code: '500185', name: 'MOIL Ltd', sector: 'Mining' },
  { code: '500186', name: 'Motilal Oswal Financial', sector: 'Finance' },
  { code: '500188', name: 'Multi Commodity Exchange', sector: 'Finance' },
  { code: '500190', name: 'Nagarjuna Fertilizers', sector: 'Fertilizers' },
  { code: '500193', name: 'National Fertilizers Ltd', sector: 'Fertilizers' },
  { code: '500195', name: 'Navin Fluorine International', sector: 'Chemicals' },
  { code: '500199', name: 'NBCC India Ltd', sector: 'Construction' },
  { code: '500200', name: 'NCC Ltd', sector: 'Construction' },
  { code: '500201', name: 'Nesco Ltd', sector: 'Infrastructure' },
  { code: '500202', name: 'NLC India Ltd', sector: 'Power' },
  { code: '500209', name: 'Procter & Gamble Hygiene', sector: 'FMCG' },
  { code: '500210', name: 'Pfizer Ltd', sector: 'Pharma' },
  { code: '500213', name: 'Phillips Carbon Black', sector: 'Chemicals' },
  { code: '500215', name: 'Radico Khaitan Ltd', sector: 'Beverages' },
  { code: '500217', name: 'Rane Holdings Ltd', sector: 'Auto Components' },
  { code: '500219', name: 'Rashtriya Chemicals & Fertilizers', sector: 'Fertilizers' },
  { code: '500220', name: 'Raymond Ltd', sector: 'Textiles' },
  { code: '500221', name: 'RHI Magnesita India Ltd', sector: 'Metals' },
  { code: '500228', name: 'Sanofi India Ltd', sector: 'Pharma' },
  { code: '500229', name: 'Saregama India Ltd', sector: 'Media' },
  { code: '500230', name: 'SBI Life Insurance Co', sector: 'Insurance' },
  { code: '500233', name: 'Schaeffler India Ltd', sector: 'Auto Components' },
  { code: '500235', name: 'Shree Cement Ltd', sector: 'Cement' },
  { code: '500236', name: 'Shriram Finance Ltd', sector: 'Finance' },
  { code: '500238', name: 'SKF India Ltd', sector: 'Auto Components' },
  { code: '500240', name: 'Solar Industries India', sector: 'Chemicals' },
  { code: '500241', name: 'Sonata Software Ltd', sector: 'IT' },
  { code: '500243', name: 'Star Health Insurance', sector: 'Insurance' },
  { code: '500245', name: 'Summit Securities Ltd', sector: 'Finance' },
  { code: '500247', name: 'Sundaram Finance Ltd', sector: 'Finance' },
  { code: '500249', name: 'Sundram Fasteners Ltd', sector: 'Auto Components' },
  { code: '500250', name: 'Suprajit Engineering Ltd', sector: 'Auto Components' },
  { code: '500251', name: 'Supreme Industries Ltd', sector: 'Plastics' },
  { code: '500253', name: 'Suven Pharmaceuticals', sector: 'Pharma' },
  { code: '500257', name: 'Tata Investment Corp Ltd', sector: 'Finance' },
  { code: '500260', name: 'Thermax Ltd', sector: 'Engineering' },
  { code: '500262', name: 'Thomas Cook India Ltd', sector: 'Tourism' },
  { code: '500265', name: 'Timken India Ltd', sector: 'Engineering' },
  { code: '500267', name: 'Titan Company Ltd', sector: 'Consumer Goods' },
  { code: '500271', name: 'Triveni Turbine Ltd', sector: 'Engineering' },
  { code: '500272', name: 'TTK Prestige Ltd', sector: 'Consumer Durables' },
  { code: '500275', name: 'UCO Bank', sector: 'Banking' },
  { code: '500278', name: 'Union Bank of India', sector: 'Banking' },
  { code: '500280', name: 'UTI Asset Management Co', sector: 'Finance' },
  { code: '500283', name: 'V-Guard Industries Ltd', sector: 'Electricals' },
  { code: '500285', name: 'Vaibhav Global Ltd', sector: 'Gems & Jewellery' },
  { code: '500289', name: 'Vesuvius India Ltd', sector: 'Engineering' },
  { code: '500290', name: 'VIP Industries Ltd', sector: 'Consumer Goods' },
  { code: '500292', name: 'Welspun Living Ltd', sector: 'Textiles' },
  { code: '500295', name: 'Welspun Corp Ltd', sector: 'Metals' },
  { code: '500296', name: 'Wendt India Ltd', sector: 'Engineering' },
  { code: '500300', name: 'West Coast Paper Mills', sector: 'Paper' },
  { code: '500302', name: 'ZF Commercial Vehicle Systems', sector: 'Auto Components' },
  { code: '500303', name: 'Zensar Technologies Ltd', sector: 'IT' },
  { code: '500306', name: 'Zydus Lifesciences Ltd', sector: 'Pharma' },
  { code: '500312', name: 'RITES Ltd', sector: 'Infrastructure' },
  { code: '500314', name: 'SAIL', sector: 'Metals' },
  { code: '500317', name: 'SBI Cards & Payment Services', sector: 'Finance' },
  { code: '500320', name: 'Siemens Ltd', sector: 'Engineering' },
  { code: '500331', name: 'Sobha Ltd', sector: 'Real Estate' },
  { code: '500335', name: 'SRF Ltd', sector: 'Chemicals' },
  { code: '500338', name: 'Sterlite Technologies Ltd', sector: 'Telecom' },
  { code: '500339', name: 'Sun TV Network Ltd', sector: 'Media' },
  { code: '500340', name: 'Sunteck Realty Ltd', sector: 'Real Estate' },
  { code: '500344', name: 'Tata Chemicals Ltd', sector: 'Chemicals' },
  { code: '500347', name: 'Tata Communications Ltd', sector: 'Telecom' },
  { code: '500348', name: 'Tata Consumer Products', sector: 'FMCG' },
  { code: '500350', name: 'Tata Elxsi Ltd', sector: 'IT' },
  { code: '500354', name: 'Tata Motors Ltd', sector: 'Automobile' },
  { code: '500355', name: 'Tata Power Company Ltd', sector: 'Power' },
  { code: '500356', name: 'Tata Steel Ltd', sector: 'Metals' },
  { code: '500357', name: 'Tata Technologies Ltd', sector: 'IT' },
  { code: '500360', name: 'Tech Mahindra Ltd', sector: 'IT' },
  { code: '500364', name: 'The India Cements Ltd', sector: 'Cement' },
  { code: '500367', name: 'The Indian Hotels Co', sector: 'Hotels' },
  { code: '500370', name: 'The Ramco Cements Ltd', sector: 'Cement' },
  { code: '500375', name: 'Torrent Pharmaceuticals', sector: 'Pharma' },
  { code: '500376', name: 'Torrent Power Ltd', sector: 'Power' },
  { code: '500378', name: 'Trent Ltd', sector: 'Retail' },
  { code: '500380', name: 'Trident Ltd', sector: 'Textiles' },
  { code: '500387', name: 'TVS Motor Company Ltd', sector: 'Automobile' },
  { code: '500390', name: 'UltraTech Cement Ltd', sector: 'Cement' },
  { code: '500395', name: 'UPL Ltd', sector: 'Chemicals' },
  { code: '500400', name: 'Varun Beverages Ltd', sector: 'Beverages' },
  { code: '500405', name: 'Vedanta Ltd', sector: 'Metals' },
  { code: '500410', name: 'Voltas Ltd', sector: 'Consumer Durables' },
  { code: '500415', name: 'Whirlpool of India Ltd', sector: 'Consumer Durables' },
  { code: '500420', name: 'Wipro Ltd', sector: 'IT' },
  { code: '500425', name: 'Yes Bank Ltd', sector: 'Banking' },
  { code: '500430', name: 'Zee Entertainment Enterprises', sector: 'Media' },
  { code: '500435', name: 'Zomato Ltd', sector: 'Internet' },
  { code: '500440', name: 'Zydus Wellness Ltd', sector: 'FMCG' },
  { code: '532174', name: 'ICICI Bank Ltd', sector: 'Banking' },
  { code: '532210', name: 'City Union Bank Ltd', sector: 'Banking' },
  { code: '532215', name: 'Axis Bank Ltd', sector: 'Banking' },
  { code: '532281', name: 'HCL Technologies Ltd', sector: 'IT' },
  { code: '532286', name: 'Jindal Steel & Power Ltd', sector: 'Metals' },
  { code: '532290', name: 'Jubilant FoodWorks Ltd', sector: 'Food Services' },
  { code: '532296', name: 'Glenmark Pharmaceuticals', sector: 'Pharma' },
  { code: '532300', name: 'Lupin Ltd', sector: 'Pharma' },
  { code: '532309', name: 'Marico Ltd', sector: 'FMCG' },
  { code: '532312', name: 'MRF Ltd', sector: 'Tyres' },
  { code: '532315', name: 'Oracle Financial Services', sector: 'IT' },
  { code: '532321', name: 'Page Industries Ltd', sector: 'Textiles' },
  { code: '532326', name: 'Phoenix Mills Ltd', sector: 'Real Estate' },
  { code: '532331', name: 'PI Industries Ltd', sector: 'Chemicals' },
  { code: '532343', name: 'Polycab India Ltd', sector: 'Electricals' },
  { code: '532345', name: 'Prestige Estates Projects', sector: 'Real Estate' },
  { code: '532348', name: 'PVR Inox Ltd', sector: 'Entertainment' },
  { code: '532352', name: 'RBL Bank Ltd', sector: 'Banking' },
  { code: '532354', name: 'Relaxo Footwears Ltd', sector: 'Footwear' },
  { code: '532358', name: 'Route Mobile Ltd', sector: 'IT' },
  { code: '532371', name: 'Samvardhana Motherson Intl', sector: 'Auto Components' },
  { code: '532374', name: 'Sona BLW Precision Forgings', sector: 'Auto Components' },
  { code: '532378', name: 'Tanla Platforms Ltd', sector: 'IT' },
  { code: '532382', name: 'Tata Metaliks Ltd', sector: 'Metals' },
  { code: '532386', name: 'Tata Teleservices', sector: 'Telecom' },
  { code: '532391', name: 'TeamLease Services Ltd', sector: 'Staffing' },
  { code: '532400', name: 'Aarti Industries Ltd', sector: 'Chemicals' },
  { code: '532406', name: 'Aditya Birla Fashion', sector: 'Retail' },
  { code: '532410', name: 'Adani Enterprises Ltd', sector: 'Conglomerate' },
  { code: '532412', name: 'Adani Green Energy Ltd', sector: 'Renewable Energy' },
  { code: '532414', name: 'Adani Ports & SEZ Ltd', sector: 'Infrastructure' },
  { code: '532416', name: 'Adani Total Gas Ltd', sector: 'Oil & Gas' },
  { code: '532418', name: 'Adani Wilmar Ltd', sector: 'FMCG' },
  { code: '532420', name: 'Affle India Ltd', sector: 'Internet' },
  { code: '532422', name: 'Alembic Pharmaceuticals', sector: 'Pharma' },
  { code: '532424', name: 'Alkyl Amines Chemicals', sector: 'Chemicals' },
  { code: '532426', name: 'Amber Enterprises India', sector: 'Consumer Durables' },
  { code: '532428', name: 'Amrutanjan Health Care', sector: 'Pharma' },
  { code: '532430', name: 'Angel One Ltd', sector: 'Finance' },
  { code: '532432', name: 'APL Apollo Tubes Ltd', sector: 'Metals' },
  { code: '532434', name: 'Apollo Hospitals Enterprise', sector: 'Healthcare' },
  { code: '532436', name: 'Apollo Tyres Ltd', sector: 'Tyres' },
  { code: '532438', name: 'Aptus Value Housing Finance', sector: 'Finance' },
  { code: '532440', name: 'Archean Chemical Industries', sector: 'Chemicals' },
  { code: '532442', name: 'Ashoka Buildcon Ltd', sector: 'Construction' },
  { code: '532444', name: 'Asian Paints Ltd', sector: 'Paints' },
  { code: '532446', name: 'Astral Ltd', sector: 'Plastics' },
  { code: '532448', name: 'Aster DM Healthcare', sector: 'Healthcare' },
  { code: '532450', name: 'AstraZeneca Pharma India', sector: 'Pharma' },
  { code: '532452', name: 'Atul Ltd', sector: 'Chemicals' },
  { code: '532454', name: 'AU Small Finance Bank', sector: 'Banking' },
  { code: '532456', name: 'Aurobindo Pharma Ltd', sector: 'Pharma' },
  { code: '532458', name: 'Avanti Feeds Ltd', sector: 'Food Processing' },
  { code: '532460', name: 'Avenue Supermarts Ltd', sector: 'Retail' },
  { code: '532462', name: 'Bajaj Auto Ltd', sector: 'Automobile' },
  { code: '532464', name: 'Bajaj Electricals Ltd', sector: 'Electricals' },
  { code: '532466', name: 'Bajaj Finance Ltd', sector: 'Finance' },
  { code: '532468', name: 'Bajaj Finserv Ltd', sector: 'Finance' },
  { code: '532470', name: 'Bajaj Holdings & Investment', sector: 'Finance' },
  { code: '532472', name: 'Balaji Amines Ltd', sector: 'Chemicals' },
  { code: '532474', name: 'Balkrishna Industries Ltd', sector: 'Tyres' },
  { code: '532476', name: 'Bandhan Bank Ltd', sector: 'Banking' },
  { code: '532478', name: 'Bank of Baroda', sector: 'Banking' },
  { code: '532480', name: 'BASF India Ltd', sector: 'Chemicals' },
  { code: '532482', name: 'Bata India Ltd', sector: 'Footwear' },
  { code: '532484', name: 'Berger Paints India Ltd', sector: 'Paints' },
  { code: '532486', name: 'Bharat Dynamics Ltd', sector: 'Defence' },
  { code: '532488', name: 'Bharat Electronics Ltd', sector: 'Defence' },
  { code: '532490', name: 'Bharat Heavy Electricals', sector: 'Engineering' },
  { code: '532492', name: 'Bharat Petroleum Corp', sector: 'Oil & Gas' },
  { code: '532494', name: 'Biocon Ltd', sector: 'Pharma' },
  { code: '532496', name: 'Birla Tyres Ltd', sector: 'Tyres' },
  { code: '532498', name: 'Blue Dart Express Ltd', sector: 'Logistics' },
  { code: '532500', name: 'Blue Star Ltd', sector: 'Consumer Durables' },
  { code: '532502', name: 'Bombay Burmah Trading', sector: 'Plantations' },
  { code: '532504', name: 'Borosil Renewables Ltd', sector: 'Renewable Energy' },
  { code: '532506', name: 'Bosch Ltd', sector: 'Auto Components' },
  { code: '532508', name: 'Brigade Enterprises Ltd', sector: 'Real Estate' },
  { code: '532510', name: 'Britannia Industries Ltd', sector: 'FMCG' },
  { code: '532512', name: 'BSE Ltd', sector: 'Finance' },
  { code: '532514', name: 'C.E. Info Systems Ltd', sector: 'IT' },
  { code: '532516', name: 'Campus Activewear Ltd', sector: 'Footwear' },
  { code: '532518', name: 'Can Fin Homes Ltd', sector: 'Finance' },
  { code: '532520', name: 'Canara Bank', sector: 'Banking' },
  { code: '532522', name: 'Caplin Point Laboratories', sector: 'Pharma' },
  { code: '532524', name: 'Carysil Ltd', sector: 'Consumer Durables' },
  { code: '532526', name: 'Castrol India Ltd', sector: 'Oil & Gas' },
  { code: '532528', name: 'CCL Products India Ltd', sector: 'Food Processing' },
  { code: '532530', name: 'CDSL Ltd', sector: 'Finance' },
  { code: '532532', name: 'Cello World Ltd', sector: 'Consumer Goods' },
  { code: '532534', name: 'Central Bank of India', sector: 'Banking' },
  { code: '532536', name: 'Central Depository Services', sector: 'Finance' },
  { code: '532538', name: 'Cholamandalam Inv & Finance', sector: 'Finance' },
  { code: '532540', name: 'CIE Automotive India Ltd', sector: 'Auto Components' },
  { code: '532542', name: 'Cipla Ltd', sector: 'Pharma' },
  { code: '532544', name: 'Clean Science & Technology', sector: 'Chemicals' },
  { code: '532546', name: 'Coal India Ltd', sector: 'Mining' },
  { code: '532548', name: 'Cochin Shipyard Ltd', sector: 'Defence' },
  { code: '532550', name: 'Coforge Ltd', sector: 'IT' },
  { code: '532552', name: 'Colgate-Palmolive India', sector: 'FMCG' },
  { code: '532554', name: 'Computer Age Management', sector: 'Finance' },
  { code: '532556', name: 'Concord Biotech Ltd', sector: 'Pharma' },
  { code: '532558', name: 'Container Corp of India', sector: 'Logistics' },
  { code: '532560', name: 'Coromandel International', sector: 'Fertilizers' },
  { code: '532562', name: 'Craftsman Automation Ltd', sector: 'Auto Components' },
  { code: '532564', name: 'CRISIL Ltd', sector: 'Finance' },
  { code: '532566', name: 'Crompton Greaves Consumer', sector: 'Consumer Durables' },
  { code: '532568', name: 'Cummins India Ltd', sector: 'Engineering' },
  { code: '532570', name: 'Cyient Ltd', sector: 'IT' },
  { code: '532572', name: 'Dabur India Ltd', sector: 'FMCG' },
  { code: '532574', name: 'Data Patterns India Ltd', sector: 'Defence' },
  { code: '532576', name: 'Deepak Nitrite Ltd', sector: 'Chemicals' },
  { code: '532578', name: 'Delhivery Ltd', sector: 'Logistics' },
  { code: '532580', name: 'Dixon Technologies India', sector: 'Electronics' },
  { code: '532582', name: "Divi's Laboratories Ltd", sector: 'Pharma' },
  { code: '532584', name: "Dr Reddy's Laboratories", sector: 'Pharma' },
  { code: '532586', name: 'Dr Lal PathLabs Ltd', sector: 'Healthcare' },
  { code: '532588', name: 'Eicher Motors Ltd', sector: 'Automobile' },
  { code: '532590', name: 'Elgi Equipments Ltd', sector: 'Engineering' },
  { code: '532592', name: 'EPL Ltd', sector: 'Packaging' },
  { code: '532594', name: 'Equitas Small Finance Bank', sector: 'Banking' },
  { code: '532596', name: 'Escorts Kubota Ltd', sector: 'Automobile' },
  { code: '532598', name: 'Ethos Ltd', sector: 'Retail' },
  { code: '532600', name: 'Exide Industries Ltd', sector: 'Auto Components' },
  { code: '532602', name: 'Federal Bank Ltd', sector: 'Banking' },
  { code: '532604', name: 'Fine Organic Industries', sector: 'Chemicals' },
  { code: '532606', name: 'Five-Star Business Finance', sector: 'Finance' },
  { code: '532608', name: 'Fortis Healthcare Ltd', sector: 'Healthcare' },
  { code: '532610', name: 'GAIL India Ltd', sector: 'Oil & Gas' },
  { code: '532612', name: 'Galaxy Surfactants Ltd', sector: 'Chemicals' },
  { code: '532614', name: 'Garware Hi-Tech Films', sector: 'Plastics' },
  { code: '532616', name: 'Gland Pharma Ltd', sector: 'Pharma' },
  { code: '532618', name: 'Global Health Ltd', sector: 'Healthcare' },
  { code: '532620', name: 'GMR Airports Infrastructure', sector: 'Infrastructure' },
  { code: '532622', name: 'Godrej Consumer Products', sector: 'FMCG' },
  { code: '532624', name: 'Godrej Properties Ltd', sector: 'Real Estate' },
  { code: '532626', name: 'Great Eastern Shipping', sector: 'Shipping' },
  { code: '532628', name: 'Greenpanel Industries', sector: 'Wood Products' },
  { code: '532630', name: 'Gujarat Gas Ltd', sector: 'Oil & Gas' },
  { code: '532632', name: 'Gujarat Narmada Valley Fert', sector: 'Fertilizers' },
  { code: '532634', name: 'Gujarat Pipavav Port Ltd', sector: 'Infrastructure' },
  { code: '532636', name: 'Gujarat State Petronet Ltd', sector: 'Oil & Gas' },
  { code: '532638', name: 'Gulf Oil Lubricants Ltd', sector: 'Oil & Gas' },
  { code: '532640', name: 'HAL', sector: 'Defence' },
  { code: '532642', name: 'Happiest Minds Technologies', sector: 'IT' },
  { code: '532644', name: 'HCL Infosystems Ltd', sector: 'IT' },
  { code: '532646', name: 'HDFC Bank Ltd', sector: 'Banking' },
  { code: '532648', name: 'HDFC Life Insurance Co', sector: 'Insurance' },
  { code: '532650', name: 'Hero MotoCorp Ltd', sector: 'Automobile' },
  { code: '532652', name: 'Hindustan Aeronautics Ltd', sector: 'Defence' },
  { code: '532654', name: 'Hindustan Unilever Ltd', sector: 'FMCG' },
  { code: '532656', name: 'Honasa Consumer Ltd', sector: 'FMCG' },
  { code: '532658', name: 'Honeywell Automation India', sector: 'Engineering' },
  { code: '532660', name: 'IRCTC Ltd', sector: 'Tourism' },
  { code: '532662', name: 'ICICI Prudential Life Ins', sector: 'Insurance' },
  { code: '532664', name: 'IDFC First Bank Ltd', sector: 'Banking' },
  { code: '532666', name: 'IIFL Finance Ltd', sector: 'Finance' },
  { code: '532668', name: 'Indian Bank', sector: 'Banking' },
  { code: '532670', name: 'Indian Energy Exchange Ltd', sector: 'Power' },
  { code: '532672', name: 'Indian Oil Corporation Ltd', sector: 'Oil & Gas' },
  { code: '532674', name: 'Indian Railway Finance Corp', sector: 'Finance' },
  { code: '532676', name: 'IndiaMART InterMESH Ltd', sector: 'Internet' },
  { code: '532678', name: 'Indigo Paints Ltd', sector: 'Paints' },
  { code: '532680', name: 'IndusInd Bank Ltd', sector: 'Banking' },
  { code: '532682', name: 'Info Edge India Ltd', sector: 'Internet' },
  { code: '532684', name: 'Infosys Ltd', sector: 'IT' },
  { code: '532686', name: 'Intellect Design Arena', sector: 'IT' },
  { code: '532688', name: 'InterGlobe Aviation Ltd', sector: 'Aviation' },
  { code: '532690', name: 'IOB', sector: 'Banking' },
  { code: '532692', name: 'IPCA Laboratories Ltd', sector: 'Pharma' },
  { code: '532694', name: 'ITC Ltd', sector: 'FMCG' },
  { code: '532696', name: 'JK Cement Ltd', sector: 'Cement' },
  { code: '532698', name: 'Jio Financial Services', sector: 'Finance' },
  { code: '532700', name: 'JSW Energy Ltd', sector: 'Power' },
  { code: '532702', name: 'JSW Steel Ltd', sector: 'Metals' },
  { code: '532704', name: 'Kalyan Jewellers India', sector: 'Gems & Jewellery' },
  { code: '532706', name: 'Kansai Nerolac Paints', sector: 'Paints' },
  { code: '532708', name: 'KEI Industries Ltd', sector: 'Electricals' },
  { code: '532710', name: 'Kotak Mahindra Bank Ltd', sector: 'Banking' },
  { code: '532712', name: 'KPIT Technologies Ltd', sector: 'IT' },
  { code: '532714', name: 'Krishna Institute of Medical', sector: 'Healthcare' },
  { code: '532716', name: 'L&T Finance Ltd', sector: 'Finance' },
  { code: '532718', name: 'L&T Technology Services', sector: 'IT' },
  { code: '532720', name: 'Larsen & Toubro Ltd', sector: 'Construction' },
  { code: '532722', name: 'Laurus Labs Ltd', sector: 'Pharma' },
  { code: '532724', name: 'LIC Housing Finance Ltd', sector: 'Finance' },
  { code: '532726', name: 'Life Insurance Corp of India', sector: 'Insurance' },
  { code: '532728', name: 'LTIMindtree Ltd', sector: 'IT' },
  { code: '532730', name: 'Macrotech Developers Ltd', sector: 'Real Estate' },
  { code: '532732', name: 'Mahanagar Gas Ltd', sector: 'Oil & Gas' },
  { code: '532734', name: 'Mahindra & Mahindra Ltd', sector: 'Automobile' },
  { code: '532736', name: 'Manappuram Finance Ltd', sector: 'Finance' },
  { code: '532738', name: 'Mankind Pharma Ltd', sector: 'Pharma' },
  { code: '532740', name: 'Maruti Suzuki India Ltd', sector: 'Automobile' },
  { code: '532742', name: 'Max Financial Services', sector: 'Insurance' },
  { code: '532744', name: 'Max Healthcare Institute', sector: 'Healthcare' },
  { code: '532746', name: 'Medplus Health Services', sector: 'Healthcare' },
  { code: '532748', name: 'Metropolis Healthcare Ltd', sector: 'Healthcare' },
  { code: '532750', name: 'Mphasis Ltd', sector: 'IT' },
  { code: '532752', name: 'Muthoot Finance Ltd', sector: 'Finance' },
  { code: '532754', name: 'National Aluminium Co', sector: 'Metals' },
  { code: '532756', name: 'Narayana Hrudayalaya Ltd', sector: 'Healthcare' },
  { code: '532758', name: 'Nestle India Ltd', sector: 'FMCG' },
  { code: '532760', name: 'New India Assurance Co', sector: 'Insurance' },
  { code: '532762', name: 'NHPC Ltd', sector: 'Power' },
  { code: '532764', name: 'Nippon Life India AMC', sector: 'Finance' },
  { code: '532766', name: 'NMDC Ltd', sector: 'Mining' },
  { code: '532768', name: 'NTPC Ltd', sector: 'Power' },
  { code: '532770', name: 'Nykaa (FSN E-Commerce)', sector: 'Internet' },
  { code: '532772', name: 'Oberoi Realty Ltd', sector: 'Real Estate' },
  { code: '532774', name: 'Oil & Natural Gas Corporation', sector: 'Oil & Gas' },
  { code: '532776', name: 'Olectra Greentech Ltd', sector: 'Automobile' },
  { code: '532778', name: 'One97 Communications (Paytm)', sector: 'Internet' },
  { code: '532780', name: 'PB Fintech Ltd', sector: 'Insurance' },
  { code: '532782', name: 'Persistent Systems Ltd', sector: 'IT' },
  { code: '532784', name: 'Petronet LNG Ltd', sector: 'Oil & Gas' },
  { code: '532786', name: 'Pidilite Industries Ltd', sector: 'Chemicals' },
  { code: '532788', name: 'Piramal Enterprises Ltd', sector: 'Pharma' },
  { code: '532790', name: 'Piramal Pharma Ltd', sector: 'Pharma' },
  { code: '532792', name: 'PNB Housing Finance', sector: 'Finance' },
  { code: '532794', name: 'Power Finance Corporation', sector: 'Finance' },
  { code: '532796', name: 'Power Grid Corporation', sector: 'Power' },
  { code: '532798', name: 'Punjab National Bank', sector: 'Banking' },
  { code: '532800', name: 'Quess Corp Ltd', sector: 'Staffing' },
  { code: '532802', name: 'Rajesh Exports Ltd', sector: 'Gems & Jewellery' },
  { code: '532804', name: 'Rallis India Ltd', sector: 'Chemicals' },
  { code: '532806', name: 'REC Ltd', sector: 'Finance' },
  { code: '532808', name: 'Reliance Industries Ltd', sector: 'Oil & Gas' },
  { code: '532810', name: 'Sapphire Foods India', sector: 'Food Services' },
  { code: '532812', name: 'State Bank of India', sector: 'Banking' },
  { code: '532814', name: 'Shyam Metalics & Energy', sector: 'Metals' },
  { code: '532816', name: 'Syrma SGS Technology', sector: 'Electronics' },
  { code: '532818', name: 'Tata Consultancy Services', sector: 'IT' },
  { code: '532820', name: 'Tube Investments of India', sector: 'Engineering' },
  { code: '532822', name: 'Ujjivan Small Finance Bank', sector: 'Banking' },
  { code: '532824', name: 'Utkarsh Small Finance Bank', sector: 'Banking' },
  { code: '532826', name: 'Vodafone Idea Ltd', sector: 'Telecom' },
  { code: '532828', name: 'Westlife Foodworld Ltd', sector: 'Food Services' },
  { code: '532830', name: 'Wockhardt Ltd', sector: 'Pharma' },
  { code: '532832', name: 'Zee Media Corporation', sector: 'Media' },
  { code: '532834', name: 'Zenith Drugs Ltd', sector: 'Pharma' },
  { code: '532836', name: 'Ashok Leyland Ltd', sector: 'Automobile' },
  { code: '532838', name: 'Bharti Airtel Ltd', sector: 'Telecom' },
  { code: '532840', name: 'Sun Pharmaceutical Industries', sector: 'Pharma' },
  { code: '532842', name: 'SJVN Ltd', sector: 'Power' },
  { code: '532844', name: 'Steel Authority of India', sector: 'Metals' },
  { code: '532846', name: 'Star Health Insurance', sector: 'Insurance' },
  { code: '532848', name: 'Container Corp of India', sector: 'Logistics' },
  { code: '532850', name: 'Petronet LNG Ltd', sector: 'Oil & Gas' },
];

const bseCompanies = BSE_COMPANIES.map(c => ({
  symbol: `${c.code}.BO`,
  name: c.name,
  exchange: 'BSE',
  sector: c.sector,
  industry: null,
}));

// Combine and deduplicate by name (case-insensitive)
const allCompanies = [...nseCompanies, ...bseCompanies];
const seen = new Set<string>();
const unique: any[] = [];
for (const c of allCompanies) {
  const key = c.name.toLowerCase().replace(/\s+/g, ' ').trim();
  if (!seen.has(key)) {
    seen.add(key);
    unique.push(c);
  }
}

// Write to JSON
const outPath = path.join(__dirname, '..', 'data', 'companies_data.json');
fs.writeFileSync(outPath, JSON.stringify(unique, null, 2));
console.log(`Wrote ${unique.length} unique companies to ${outPath}`);
console.log(`  NSE: ${nseCompanies.length}`);
console.log(`  BSE entries: ${bseCompanies.length}`);
console.log(`  Deduplicated total: ${unique.length}`);
